version: 2
jobs:

  build:
    docker:
      - image: circleci/node:8.9.4
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Test
          command: npm run test-ci
      - store_test_results:
          path: test-report.xml
      - store_artifacts:
          path: coverage
          prefix: coverage
      - save_cache:
          paths:
            - ~/repo
          key: built-project-{{ .BuildNum }}

  deploy:
    docker:
      - image: circleci/node:8.9.4
    working_directory: ~/repo
    steps:
      - restore_cache:
          keys:
          - built-project-{{ .BuildNum }}
          - built-project-
      - run:
          name: Run heroku setup script
          command: bash .circleci/setup-heroku.sh
      - run:
          name: Deploy Master to Heroku
          command: git push --force https://git.heroku.com/morsmail.git HEAD:master
      - run:
          name: Restart Heroku
          command: heroku restart --app morsmail

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
